### ISSUE TITLE
error: ‘dbus_connection_send_with_reply_set_notify’ was not declared in this scope #23

### ISSUE THREAD

**Issue by VishwanathB-123** [COVESA/capicxx-core-runtime#29]
vishwa@ubuntu:~/vishwa/myCode/trydbus/capicxx-core-runtime/build/capicxx-dbus-runtime/build$ make
[ 4%] Building CXX object CMakeFiles/CommonAPI-DBus.dir/src/CommonAPI/DBus/DBusConnection.cpp.o
/home/vishwa/vishwa/myCode/trydbus/capicxx-core-runtime/build/capicxx-dbus-runtime/src/CommonAPI/DBus/DBusConnection.cpp: In member function ‘virtual bool CommonAPI::DBus::DBusConnection::sendDBusMessageWithReplyAsync(const CommonAPI::DBus::DBusMessage&, std::unique_ptrCommonAPI::DBus::DBusProxyConnection::DBusMessageReplyAsyncHandler, const CommonAPI::CallInfo*) const’:
/home/vishwa/vishwa/myCode/trydbus/capicxx-core-runtime/build/capicxx-dbus-runtime/src/CommonAPI/DBus/DBusConnection.cpp:877:26: error: ‘dbus_connection_send_with_reply_set_notify’ was not declared in this scope; did you mean ‘dbus_connection_send_with_reply_and_block’?
877 | libdbusSuccess = dbus_connection_send_with_reply_set_notify(connection_,
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| dbus_connection_send_with_reply_and_block
make[2]: *** [CMakeFiles/CommonAPI-DBus.dir/build.make:102: CMakeFiles/CommonAPI-DBus.dir/src/CommonAPI/DBus/DBusConnection.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:188: CMakeFiles/CommonAPI-DBus.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

Patch command :
vishwa@ubuntu:/$ sudo patch -d/ /home/vishwa/vishwa/myCode/trydbus/capicxx-core-runtime/build/capicxx-dbus-runtime/src/CommonAPI/DBus/DBusConnection.cpp <~/vishwa/myCode/trydbus/capicxx-core-runtime/build/capicxx-dbus-runtime/src/dbus-patches/capi-dbus-add-send-with-reply-set-notify.patch
patching file /home/vishwa/vishwa/myCode/trydbus/capicxx-core-runtime/build/capicxx-dbus-runtime/src/CommonAPI/DBus/DBusConnection.cpp
Hunk #1 FAILED at 3482.
1 out of 1 hunk FAILED -- saving rejects to file /home/vishwa/vishwa/myCode/trydbus/capicxx-core-runtime/build/capicxx-dbus-runtime/src/CommonAPI/DBus/DBusConnection.cpp.rej
patching file /home/vishwa/vishwa/myCode/trydbus/capicxx-core-runtime/build/capicxx-dbus-runtime/src/CommonAPI/DBus/DBusConnection.cpp
Hunk #1 FAILED at 229.
1 out of 1 hunk FAILED -- saving rejects to file /home/vishwa/vishwa/myCode/trydbus/capicxx-core-runtime/build/capicxx-dbus-runtime/src/CommonAPI/DBus/DBusConnection.cpp.rej

**Comment by goncaloalmeida** [comment]
@VishwanathB-123 this problem is still reproducible?
