### ISSUE TITLE
Linking Dependency Build Error

### ISSUE THREAD

**Issue by aravinds2018** [COVESA/capicxx-core-runtime#37]
With CommonAPI library iam able to generate code and build binary in ubuntu 14, but unable to build the  binary in ubuntu 22. What should be the possible reasons?
![image](https://github.com/COVESA/capicxx-core-runtime/assets/104155195/fd368f64-9288-4ed5-b4d5-2712f73b9b4e)

**Comment by goncaloalmeida** [comment]
@aravinds2018 this problem is still reproducible?
